version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  batch_processor:
    build:
      context: .
      dockerfile: batch_processor/Dockerfile
    depends_on:
      - db
    environment:
      # Use Docker Compose variable substitution for flexibility
      # Default to Docker service hostnames, but allow override from host
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:pass@db:5432/mlops_db}
      - PROMETHEUS_PUSHGATEWAY=${PROMETHEUS_PUSHGATEWAY:-pushgateway:9091}
    volumes:
       - ./batch_processor/input_data:/app/input_data
    # Run with --reprocess-all to reprocess all data by default
    command: ["python", "-m", "batch_processor.main", "--reprocess-all"]

  api_service:
    build: ./api_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:pass@db:5432/mlops_db}
      - PROMETHEUS_PUSHGATEWAY=${PROMETHEUS_PUSHGATEWAY:-pushgateway:9091}
    volumes:
      - ./churn_model.pickle:/app/churn_model.pickle

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

volumes:
  pgdata:
