global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_service'
    static_configs:
      - targets: ['api_service:8000']
  - job_name: 'batch_processor' # Metrics pushed via Pushgateway
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'pushgateway' # To scrape Pushgateway itself (optional, for meta-monitoring)
    static_configs:
      - targets: ['pushgateway:9091'] 