server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<docker_ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}[.,]\d+) [\-|\|] (?P<level>[A-Z]+) +[\-|\|] (?P<module>[\w\.]+):(?P<function>\w+):(?P<line>\d+) [\-|\|] (?P<msg>.*)$'
      - json:
          expressions:
            level: level
            module: module
            func: func
      - labels:
          level:
          module:
          function:
      - output:
          source: msg