{
 "title": "Customer Churn Dashboard1",
 "tags": [
  "churn",
  "customer",
  "mlops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New Customers Over Time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT loaded_at AS time, COUNT(*) AS new_customers FROM customer_data GROUP BY loaded_at ORDER BY loaded_at"
    }
   ]
  },
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_predictions FROM churn_predictions"
    }
   ]
  },
  {
   "title": "Total Customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_customers FROM customer_data"
    }
   ]
  },
  {
   "title": "Contract Type Distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT contract, COUNT(*) AS count FROM customer_data GROUP BY contract"
    }
   ]
  },
  {
   "title": "Churn Probability Distribution",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT ROUND(churn_probability_churn::numeric, 1) AS probability, COUNT(*) AS count FROM churn_predictions GROUP BY probability ORDER BY probability"
    }
   ]
  },
  {
   "title": "Churn Prediction Distribution",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT churn_prediction, COUNT(*) AS count FROM churn_predictions GROUP BY churn_prediction"
    }
   ]
  },
  {
   "title": "Average Churn Probability Over Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prediction_timestamp AS time, AVG(churn_probability_churn) AS avg_churn_prob FROM churn_predictions GROUP BY prediction_timestamp ORDER BY prediction_timestamp"
    }
   ]
  }
 ]
}