name: Daily Batch Processing

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  batch-process:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: mlops_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://user:pass@localhost:5432/mlops_db
      PROMETHEUS_PUSHGATEWAY: localhost:9091
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r batch_processor/requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run batch processor for database_input.csv
        run: |
          python batch_processor/main.py --input batch_processor/database_input.csv

      - name: Run batch processor for database_input1.csv
        run: |
          python batch_processor/main.py --input batch_processor/database_input1.csv

      - name: Run batch processor for database_input2.csv
        run: |
          python batch_processor/main.py --input batch_processor/database_input2.csv 