name: Daily Batch Processing

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  batch-process:
    runs-on: self-hosted

    env:
      DATABASE_URL: postgresql://user:pass@localhost:5432/mlops_db
      PROMETHEUS_PUSHGATEWAY: localhost:9091
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build batch processor Docker image
        run: docker build -t batch-processor .

      - name: List input CSV files (debug)
        run: |
          ls -l batch_processor/input_data/*.csv || echo "No CSV files found"

      - name: Run batch processor container
        run: |
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -e PROMETHEUS_PUSHGATEWAY="$PROMETHEUS_PUSHGATEWAY" \
            -v $(pwd)/batch_processor/input_data:/app/input_data \
            -v $(pwd)/churn_model.pickle:/app/churn_model.pickle \
            batch-processor python -m batch_processor.main --reprocess-all