name: Daily Batch Processing

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  batch-process:
    runs-on: self-hosted

    env:
      DATABASE_URL: postgresql://user:pass@db:5432/mlops_db
      PROMETHEUS_PUSHGATEWAY: localhost:9091
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to repo directory
        run: cd ${{ github.workspace }}

      - name: Build and start batch processor
        run: docker-compose up --build --abort-on-container-exit batch_processor